### PR TITLE
Improvement: wraps tainers create with retry logic

### PR DESCRIPTION
**Pull request by brianbianco**
I have left the changing of the metadata version to you, but this adds retry logic for tainer creation.

### CODE REVIEW

**Comment by brianbianco** [comment]
I wonder if I should raise the exception again after the 3 failed attempts?

**Comment by ethanrowe** [comment]
That's probably reasonable.

**Comment by ethanrowe** [comment]
I'd like to make two suggestions:
1. Have the number of retry attempts be an attribute on the resource, and by all means have it default to 3, but let the recipe author specify an alternate limit.
2. A minor nit, but this variable name is misleading:

``` ruby
container = new_resource.tainer.create
```

It's misleading because `container` isn't necessarily a container (or a `Tainer::Specification`); if the underlying container already existed, then `container` will be `false`.

It's hardly the end of the world, but given that this is interested in the truthiness of `container` and not whether or not it's a `Tainer::Specification`, you might want the variable to be named `created` or something more intuitive to its purpose.

**Comment by brianbianco** [comment]
I'm not sure "created" is a reasonable name for the variable either.  It could contain false or it could container an object which is the container itself (or at least a specification for it).  That is why I chose the name container.

Either it is a container object or, it is FALSE that there is a container object in there (perhaps you should have been returning nil, not false?  It would seem more consistent since it DOES return a container object some of the time.)

As for the retry attempts not being configurable.  I did that in an attempt to keep things clean and simple.  If you want me to add that functionality I certainly can.  I felt it was maybe unnecessary.

**Comment by ethanrowe** [comment]
So, I don't have particularly strong feelings on the variable name; I think you're emphasizing what it might be, while I'm emphasizing its logical meaning.  But whatever; I don't care that much.

How about this: leave the variable however the hell you want, but put the retry count in a resource attribute.  Compromise.

**Pull request merged**
